local tools = dofile("build-support/tools.lua")
assert(type(tools.quote) == "function")
assert(type(tools.command_exists) == "function")
assert(type(tools.pdfcpu) == "function")
assert(tools.quote("a b.pdf"):match("a b%.pdf"))
print("tagpax build tools: ok")
