schema = 2
bundle_preset = "OSG lecture/1"

[project]
id = "project-config-test"
tex_directory = "."
tex_config = "projectconfig-test.tex"

[targets.defaults]
languages = ["de"]
default_language = "de"
