#!/usr/bin/env texlua
-- Scans the bundle's LaTeX packages for \Provides* declarations, reports
-- whether the files generated from one docstrip source agree on version
-- and date, and refreshes the module-version table in README.md between
-- the "MODULE VERSIONS" markers.
--
-- Usage: texlua tools/update-bundle-manifest.lua   (run from the bundle root)

-- Distribution compatibility has a single point of truth: the expectations
-- evaluated by the "Distribution compatibility" GitHub Actions workflow.
local COMPAT_HEADERS = { "TL 2024", "TL 2025", "TL current" }
local WORKFLOW_TO_TABLE = {
  ["osglecture-modes-core"] = "osglecture-modes",
}
local EXPECTATION_MARK = {
  pass = ":green_circle:",
  fail = ":red_circle:",
  ["n/a"] = ":white_circle:",
}

-- Capability rows are placed directly after the module they extend.
local capabilities_after = {
  ["osglecture-modes"] = {
    "ltx-talk support (osglecture + osglecture-modes)",
    lua = ":full_moon:"
  },
}

local versions = dofile("tools/bundle-versions.lua")
local read_file = versions.read_file

local function unquote(value)
  return value:match('^"(.*)"$') or value:match("^'(.*)'$") or value
end

-- This deliberately parses only the small, regular component matrix in our
-- own workflow rather than pretending to be a general YAML parser.
local function read_workflow_compat(path)
  local content = assert(read_file(path), "cannot read compatibility workflow: " .. path)
  local result = {}
  local in_components = false
  local current

  for line in (content .. "\n"):gmatch("([^\n]*)\n") do
    if line:match("^%s*component:%s*$") then
      in_components = true
    elseif in_components and line:match("^%s*distribution:%s*$") then
      break
    elseif in_components then
      local name = line:match("^%s*%- name:%s*(.-)%s*$")
      if name then
        name = unquote(name)
        name = WORKFLOW_TO_TABLE[name] or name
        assert(not result[name], "duplicate compatibility table entry: " .. name)
        current = {}
        result[name] = current
      elseif current then
        local distribution, expectation =
          line:match("^%s*expect_([%w]+):%s*([^%s#]+)")
        if distribution == "2024" or distribution == "2025" or
           distribution == "current" then
          expectation = unquote(expectation)
          local mark = EXPECTATION_MARK[expectation]
          assert(mark, "unknown compatibility expectation: " .. expectation)
          current[distribution] = mark
        end
      end
    end
  end

  local ordered = {}
  for name, values in pairs(result) do
    assert(values["2024"] and values["2025"] and values.current,
      "incomplete compatibility expectations for " .. name)
    ordered[name] = { values["2024"], values["2025"], values.current }
  end
  return ordered
end

local workflow_compat = read_workflow_compat(".github/workflows/compatibility.yml")

local report = versions.scan()

-- Console report, flagging mismatches within one module.
local any_mismatch = false
for _, r in ipairs(report) do
  if #r.entries == 0 then
    print(string.format("%-20s (no \\Provides declarations found)", r.name))
  elseif r.consistent then
    print(string.format(
      "%-20s %-10s %-12s [%d file(s), consistent]",
      r.name, r.version_list[1], r.date_list[1], #r.entries))
  else
    any_mismatch = true
    print(string.format("%-20s MIXED: %s", r.name, table.concat(r.version_list, ", ")))
    for _, e in ipairs(r.entries) do
      print(string.format(
        "    %-30s %-10s %-12s (%s)%s", e.package, e.version, e.date, e.file,
        e.excluded and "  [excluded from consistency check]" or ""))
    end
  end
end

-- Markdown table for README.md: version/date/file-count plus compatibility
-- expectations read from the workflow above.
local header_cells = { "Module", "Version", "Date", "Files", "Lua" }
local hformat = "|" .. string.rep("---|", 4)
  .. string.rep(":---:|", 1 + #COMPAT_HEADERS)
for _, h in ipairs(COMPAT_HEADERS) do table.insert(header_cells, h) end
local lines = {
  "<!-- BEGIN MODULE VERSIONS " ..
    "(generated by tools/update-bundle-manifest.lua; " ..
    "compatibility from .github/workflows/compatibility.yml) -->",
  "| " .. table.concat(header_cells, " | ") .. " |",
  hformat,
}
-- Notes are numbered in table order and rendered as footnotes right below
-- the table, inside the generated block, so the marker in the name cell
-- and its definition can never drift apart or survive a module's removal.
local footnotes = {}
for _, r in ipairs(report) do
  local version_cell, date_cell, lua_cell
  if #r.entries == 0 then
    version_cell, date_cell, lua_cell = "n/a", "n/a","n/a"
  elseif r.consistent then
    version_cell, date_cell = r.version_list[1], r.date_list[1]
  else
    version_cell = "mixed (" .. table.concat(r.version_list, ", ") .. ")"
    date_cell = "mixed (" .. table.concat(r.date_list, ", ") .. ")"
  end
  lua_cell = r.lua
  local compat = assert(workflow_compat[r.name],
    "no workflow compatibility expectations for " .. r.name)
  local name_cell = r.name
  if r.note then
    table.insert(footnotes, r.note)
    name_cell = name_cell .. "[^" .. #footnotes .. "]"
  end
  local row_cells = { name_cell, version_cell, date_cell, tostring(#r.entries), lua_cell }
  for _, c in ipairs(compat) do table.insert(row_cells, c) end
  table.insert(lines, "| " .. table.concat(row_cells, " | ") .. " |")
  for _, name in ipairs(capabilities_after[r.name] or {}) do
    local capability_compat = assert(workflow_compat[name],
      "no workflow compatibility expectations for " .. name)
    local capability_cells = { name, "n/a", "n/a", "n/a", ":full_moon:" }
    for _, c in ipairs(capability_compat) do
      table.insert(capability_cells, c)
    end
    table.insert(lines,
      "| " .. table.concat(capability_cells, " | ") .. " |")
  end
end
for i, note in ipairs(footnotes) do
  table.insert(lines, "[^" .. i .. "]: " .. note)
end
table.insert(lines, "<!-- END MODULE VERSIONS -->")
local table_block = table.concat(lines, "\n")

-- Splice the table into README.md between the markers.
local readme_path = "README.md"
local readme = read_file(readme_path)
if readme then
  local escaped_block = table_block:gsub("%%", "%%%%")
  local new_readme, count = readme:gsub(
    "<!%-%- BEGIN MODULE VERSIONS.-END MODULE VERSIONS %-%->",
    escaped_block
  )
  if count == 0 then
    print("\nNote: no BEGIN/END MODULE VERSIONS marker pair found in "
      .. readme_path .. "; table not inserted.")
  else
    local out = io.open(readme_path, "w")
    out:write(new_readme)
    out:close()
    print("\n" .. readme_path .. " module-version table refreshed.")
  end
else
  print("\nNote: " .. readme_path .. " not found; table not inserted.")
end

if any_mismatch then
  print("\nSome modules have files sharing one docstrip source but "
    .. "differing \\Provides version/date; consider syncing them.")
end
