package OLLM::BuildFile;

use v5.30;
use strict;
use warnings;

use Digest::SHA qw(sha256_hex);
use File::Basename qw(basename);
use File::Spec;
use File::Temp qw(tempfile);
use JSON::PP;

our $VERSION = '0.1.0';
our $SCHEMA = 1;

sub build_spec {
  my ($class, %arg) = @_;
  my $resolved = $arg{resolved} // die "missing resolved configuration";
  my $request = $resolved->{request};
  my $configuration = $resolved->{configuration};
  die "build files require series context"
    if $request->{context} ne 'series';
  die "build files require one concrete target"
    if !defined $request->{target} || $request->{all};
  die "build files require one concrete language"
    if !defined $request->{language};

  my $unit_directory = $arg{unit_directory} // '.';
  my $physical_unit = basename(File::Spec->rel2abs($unit_directory));
  my ($number, $profile, $role, $slug) = _parse_unit($physical_unit);
  my $target = $configuration->{definitions}{targets}{$request->{target}}
    // die "resolved target '$request->{target}' has no definition";
  my $doctype = $target->{doctype};
  my $job_id = join '-',
    $request->{series_id}, $number, $doctype, $request->{language}, $slug;

  my $config_signature = sha256_hex(
    JSON::PP->new->canonical->encode({
      definitions => $configuration->{definitions}{definition_signature},
      target      => $request->{target},
      doctype     => $doctype,
      language    => $request->{language},
      physical_unit => $physical_unit,
    }),
  );
  return {
    schema              => $SCHEMA,
    job_id              => $job_id,
    context             => 'series',
    series_id           => $request->{series_id},
    physical_unit       => $physical_unit,
    physical_number     => $number,
    unit_profile        => $profile,
    unit_role           => $role,
    unit_id             => $slug,
    target              => $request->{target},
    doctype             => $doctype,
    language            => $request->{language},
    available_languages => $arg{manifest}{languages}{available},
    language_map        => $arg{manifest}{languages}{map} // {},
    profile             => $configuration->{definitions}{profile}{reference},
    config_signature    => $config_signature,
  };
}

sub render {
  my ($class, $spec) = @_;
  my @languages = map { _tex_atom($_) } @{ $spec->{available_languages} };
  my @map = map {
    _tex_atom($_) . '=' . _tex_atom($spec->{language_map}{$_})
  } sort keys %{ $spec->{language_map} };
  my @lines = (
    '% Generated by OLLM. Do not edit.',
    "\\OsgLectureBuildSetup{",
    "  schema={" . $spec->{schema} . "},",
    "  job-id={" . _tex_atom($spec->{job_id}) . "},",
    "  context={" . _tex_atom($spec->{context}) . "},",
    "  series-id={" . _tex_atom($spec->{series_id}) . "},",
    "  physical-unit={" . _tex_atom($spec->{physical_unit}) . "},",
    "  physical-number={" . _tex_atom($spec->{physical_number}) . "},",
    "  unit-profile={" . _tex_atom($spec->{unit_profile}) . "},",
    "  unit-role={" . _tex_atom($spec->{unit_role}) . "},",
    "  unit-id={" . _tex_atom($spec->{unit_id}) . "},",
    "  target={" . _tex_atom($spec->{target}) . "},",
    "  doctype={" . _tex_atom($spec->{doctype}) . "},",
    "  language={" . _tex_atom($spec->{language}) . "},",
    "  available-languages={" . join(',', @languages) . "},",
    "  language-map={" . join(',', @map) . "},",
    "  profile={" . _tex_atom($spec->{profile}) . "},",
    "  config-signature={" . _tex_atom($spec->{config_signature}) . "}",
    "}",
    '',
  );
  return join "\n", @lines;
}

sub write_atomic {
  my ($class, $path, $content) = @_;
  my ($volume, $directories, $filename) = File::Spec->splitpath($path);
  $directories = '.' if $directories eq '';
  my ($handle, $temporary) = tempfile('.ollm-build-XXXXXX', DIR => $directories);
  binmode $handle, ':raw';
  print {$handle} $content or die "cannot write '$temporary': $!";
  close $handle or die "cannot close '$temporary': $!";
  if (-f $path) {
    open my $old, '<:raw', $path or die "cannot read '$path': $!";
    local $/;
    my $existing = <$old>;
    close $old;
    if ($existing eq $content) {
      unlink $temporary or die "cannot remove '$temporary': $!";
      return 0;
    }
  }
  if (!rename $temporary, $path) {
    my $rename_error = $!;
    if ($^O eq 'MSWin32' && -f $path) {
      my $backup = "$path.ollm-old-$$";
      rename $path, $backup
        or die "cannot prepare Windows replacement of '$path': $!";
      if (!rename $temporary, $path) {
        my $replacement_error = $!;
        rename $backup, $path
          or die "cannot replace '$path' ($replacement_error) or restore it: $!";
        die "cannot replace '$path' with '$temporary': $replacement_error";
      }
      unlink $backup or die "cannot remove replaced build file '$backup': $!";
    } else {
      die "cannot replace '$path' with '$temporary': $rename_error";
    }
  }
  return 1;
}

sub _parse_unit {
  my ($name) = @_;
  die "invalid series unit directory '$name'; expected "
    . "<three digits><optional profile>-<optional role-><slug>"
    if $name !~ /\A(\d{3})([a-z]{0,2})-(?:(a|e|i)-)?(.+)\z/;
  my ($number, $profile, $role, $slug) = ($1, $2, $3 // 'content', $4);
  die "invalid empty unit slug in '$name'" if $slug eq '';
  return ($number, $profile, $role, $slug);
}

sub _tex_atom {
  my ($value) = @_;
  $value //= '';
  die "value '$value' cannot be represented safely in a TeX build file"
    if $value !~ /\A[A-Za-z0-9 ._+\/=-]*\z/;
  return $value;
}

1;
